DROP TABLE IF EXISTS maps CASCADE;
CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES user(id) ON DELETE CASCADE,
  coord_id INTEGER REFERENCES coord_id ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL
);
